### ISSUE TITLE
Fall 2017 Event - Preliminary Quality Review

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-tf2-blindfrag#2]
- [x] Update MM / SM to latest
- [x] Make sure linux files are in `dist.linux` and that generic files are in `dist`
- [x] Verify advertisements works
- [x] Verify `sm_admin` works
- [x] Verify MOTD works
- [x] Verify your custom plugin is installed and working (dumps info to console on startup)
- [x] Verify LL config is loading
- [x] Verify only heavy class can be selected

When testing use image name of `lacledeslan/gamesvr-tf2-blindfrag` (`-srcds` and `:linux` are no longer necessary).

**Comment by JustinBenedick** [comment]
updated sm/mm and sorted files 83c5b27

**Comment by dudleycodes** [comment]
@JustinBenedick can this be closed? If so please close it. Thanks 🥇
