### ISSUE TITLE
Need Files that are Unique MM/SM Files

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-tf2-blindfrag#3]
Please get me a .zip of the MM/SM files that are unique to this repo via SLACK so that I can put them back in after I clobber everything by adding the shared repos for `sourcemod.linux` and `sourcemod-configs`.

**Comment by JustinBenedick** [comment]
Its one file  https://forums.alliedmods.net/showthread.php?p=642353
Classrestrict.smx

**Comment by dudleycodes** [comment]
Got it. Refactoring repo and testing builds. Once it looks ok to me I'll open another issue in this repo for you to verify.
